spring:
  application:
    name: journalapp

  data:
    mongodb:
      uri: mongodb+srv://Anish041:Anish9417@cluster0.rdpmn.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      # username: myjournaluser
      # password: mypassword
      auto-index-creation: true
  main:
    allow-circular-references: true

logging:
  level:
    com:
      example:
        journalapp: DEBUG


server:
  port: 8081
  servlet:
    context-path: /journal